import { useEffect, useState } from 'react'
import { Header } from '../components/layout/Header'
import { Footer } from '../components/layout/Footer'
import { BookingFormModal } from '../components/BookingForm'
import { PhoneIcon } from '../components/icons/PhoneIcon'
import { CheckIcon } from '../components/icons/CheckIcon'
import { ShieldHeartIcon } from '../components/icons/ShieldHeartIcon'
import { ArrowRightIcon } from '../components/icons/ArrowRightIcon'
import imgTyres from '../assets/images/servicekort_tyres.jpg'

type PriceEntry = { label?: string; prefix?: string; amount?: string; unit?: string; contactText?: string }
type ServiceCardProps = { title: string; description: string; priceData: PriceEntry[]; imagePlaceholder: string; onBookingClick: () => void }

const tyreServices: Omit<ServiceCardProps, 'onBookingClick'>[] = [
  { title: 'Hjulskifte', description: 'Dags att byta till sommar- eller vinterdäck? Vi ser till att bytet går snabbt, smidigt och säkert. Vi kontrollerar mönsterdjup, slitage och lufttryck samt ser över synliga bromskomponenter. Efterdragning av hjulbultarna efter cirka 10 mil ingår kostnadsfritt.', priceData: [{ label: 'Personbil', amount: '350 kr' }, { label: 'SUV & lätt lastbil', amount: '500 kr' }], imagePlaceholder: imgTyres },
  { title: 'Däckförvaring', description: 'Slipp tunga hjul och frigör plats hemma. Vi grovtvättar och kontrollerar hjulen vid inlämning, förvarar dem skyddade från UV-ljus och temperatursvängningar och kontaktar dig via SMS inför nästa säsongsskifte. Om däcken börjar bli slitna hör vi av oss i god tid.', priceData: [{ label: 'Personbil', amount: '890 kr' }, { label: 'SUV & lätt lastbil', amount: '990 kr' }], imagePlaceholder: imgTyres },
  { title: 'Omläggning av däck', description: 'När nya däck ska monteras på fälgarna utför vi omläggningen med precision, monterar nya ventiler och balanserar hjulen så att allt sitter rätt från första kilometern.', priceData: [{ prefix: 'Från', amount: '180 kr', unit: 'per däck' }], imagePlaceholder: imgTyres },
  { title: 'Hjulinställning', description: 'Rätt hjulinställning bidrar till jämnare däckslitage, stabilare vägegenskaper och lägre rullmotstånd. Vi utför fackmässig fyrhjulsinställning med modern utrustning.', priceData: [{ prefix: 'Från', amount: '1 495 kr' }], imagePlaceholder: imgTyres },
  { title: 'Däckbalansering', description: 'Vibrationer i ratten vid vissa hastigheter är ofta ett tecken på obalans. Vi mäter hjulen med precisionsutrustning och kompenserar obalansen med rätt vikter. Det ger lugnare körning och minskar onödigt slitage på däck, styrning, fjädring och chassikomponenter.', priceData: [{ contactText: 'Kontakta oss för pris' }], imagePlaceholder: imgTyres },
  { title: 'Punkteringslagning', description: 'Har du fått punktering? Vi inspekterar skadan och bedömer om däcket kan repareras säkert. När en fackmässig lagning är möjlig hjälper vi dig tillbaka på vägen utan onödigt dröjsmål.', priceData: [{ contactText: 'Kontakta oss för pris' }], imagePlaceholder: imgTyres },
]

function ServiceCard({ title, description, priceData, imagePlaceholder, onBookingClick }: ServiceCardProps) {
  const isContactPrice = priceData.some((price) => price.contactText)
  return <article className="tyres-page__service-card" aria-labelledby={`service-${title}`}>
    <div className="tyres-page__service-image"><img src={imagePlaceholder} alt="Platshållarbild för däckservice" loading="lazy" /><span>Bild kommer</span></div>
    <div className="tyres-page__service-content"><h3 id={`service-${title}`}>{title}</h3><p>{description}</p>
      <div className="tyres-page__prices" aria-label={`Pris för ${title}`}>{priceData.map((price) => price.contactText ? <p className="tyres-page__contact-price" key={price.contactText}>{price.contactText}</p> : <div className="tyres-page__price-row" key={`${price.label}-${price.amount}`}>
        {price.label && <span className="tyres-page__price-label">{price.label}</span>}<span className="tyres-page__price-value">{price.prefix && <span>{price.prefix}</span>}<strong>{price.amount}</strong>{price.unit && <small>{price.unit}</small>}</span>
      </div>)}</div>
      <button type="button" className="tyres-page__card-cta" onClick={onBookingClick}>{isContactPrice ? 'Kontakta oss' : 'Boka tid'}<ArrowRightIcon aria-hidden="true" /></button>
    </div>
  </article>
}

export default function DackservicePage() {
  const [isModalOpen, setIsModalOpen] = useState(false)
  const openModal = () => setIsModalOpen(true)
  useEffect(() => { window.scrollTo(0, 0) }, [])
  return <><Header onBookingClick={openModal} /><main className="tyres-page">
    <section className="tyres-page__hero" aria-labelledby="tyres-hero-title"><div className="container tyres-page__container"><div className="section-eyebrow"><span className="eyebrow-line" aria-hidden="true" />Däckverkstad i Brynäs, Gävle</div><h1 id="tyres-hero-title">Däckservice &amp; <span className="title-accent">Hjulskifte</span> i Gävle</h1><p>Vi hjälper dig med hjulskifte, montering, balansering, hjulinställning, punkteringslagning och däckhotell — med omtanke om säkerhet, körkomfort och dina hjul.</p><div className="tyres-page__actions"><button type="button" className="tyres-page__button tyres-page__button--primary" onClick={openModal}>Boka tid</button><a className="tyres-page__button tyres-page__button--outline" href="tel:0705533395"><PhoneIcon />Ring oss: 070-553 33 95</a></div></div></section>
    <section className="tyres-page__dates" aria-labelledby="tyres-dates-title"><div className="container tyres-page__container"><div className="tyres-page__check-card"><div><div className="section-eyebrow"><span className="eyebrow-line" aria-hidden="true" />Lagkrav och datum</div><h2 id="tyres-dates-title">Viktiga datum &amp; lagkrav för <span className="title-accent">vinterdäck</span></h2><p>I Sverige gäller särskilda lagar för när vinterdäck krävs och när dubbdäck är tillåtna. För att ett vinterdäck ska räknas som godkänt krävs numera den officiella 3PMSF-märkningen (symbolen med alptopp och snöflinga).</p></div><ul className="tyres-page__checklist"><li><CheckIcon /><span><strong>1 dec – 31 mar:</strong> Krav på vinterdäck vid vinterväglag (minst 3 mm mönsterdjup).</span></li><li><CheckIcon /><span><strong>1 okt – 15 apr:</strong> Tillåtet med dubbdäck (även annan tid om det är eller befaras bli vinterväglag).</span></li><li><CheckIcon /><span><strong>16 apr – 30 sep:</strong> Förbud mot dubbdäck (om inte vinterväglag råder eller befaras).</span></li><li><CheckIcon /><span><strong>3PMSF-märkning:</strong> Lagstadgat krav på Three-Peak Mountain Snowflake ("alptopp/snöflinga") för godkända vinterdäck.</span></li></ul><div className="tyres-page__check-footer"><p>Boka ditt hjulskifte i god tid så slipper du köer när temperaturen faller och halkan kommer.</p><button type="button" className="tyres-page__button tyres-page__button--primary" onClick={openModal}>Boka hjulskifte</button></div></div></div></section>
    <section className="tyres-page__services" aria-labelledby="tyres-services-title"><div className="container tyres-page__container"><header className="tyres-page__section-header"><div className="section-eyebrow"><span className="eyebrow-line" aria-hidden="true" />Våra däcktjänster</div><h2 id="tyres-services-title">Allt för dina <span className="title-accent">hjul</span></h2><p>Från säsongsskifte till kontroll och reparation — välj den hjälp som passar din bil.</p><strong>Samtliga priser är inklusive moms.</strong></header><div className="tyres-page__service-grid">{tyreServices.map((service) => <ServiceCard {...service} key={service.title} onBookingClick={openModal} />)}</div></div></section>
    <section className="tyres-page__legacy" aria-labelledby="tyres-legacy-title"><div className="container tyres-page__container"><article className="tyres-page__legacy-card"><img src={imgTyres} alt="Montering och balansering av däck i däckverkstad" loading="lazy" /><div><div className="section-eyebrow section-eyebrow--dark"><span className="eyebrow-line" aria-hidden="true" />Befintlig däckservice</div><h2 id="tyres-legacy-title">Mer om vår däckservice</h2><p>Utöver skifte och balansering hjälper vi till med hjulinställning och säsongsförvaring. Vi ser över mönsterdjup, lufttryck och synliga bromskomponenter så att du får en bra överblick över hjulens skick.</p><ul>{['Däckbyte & montering', 'Balansering av hjul', 'Hjulinställning', 'Däckhotell — förvaring & tvätt', 'Däcktryckskontroll'].map((item) => <li key={item}><CheckIcon />{item}</li>)}</ul></div></article></div></section>
    <section className="tyres-page__advice" aria-labelledby="tyres-advice-title"><div className="container tyres-page__container"><div className="tyres-page__advice-grid"><div><div className="section-eyebrow"><span className="eyebrow-line" aria-hidden="true" />Råd till bilägaren</div><h2 id="tyres-advice-title">Så håller du koll på <span className="title-accent">däcken</span></h2></div><div><p>Kontrollera lufttrycket när däcken är kalla och jämför med bilens instruktionsbok. Som riktmärke är en kontroll varje månad en bra vana, och en extra kontroll inför längre resor eller säsongsskifte är klok. Rätt lufttryck ger bättre väggrepp, kortare bromssträcka, lägre bränsleförbrukning och jämnare slitage.</p><p>Lagen kräver ett minsta mönsterdjup på 1,6 mm för sommardäck och 3 mm vid vinterväglag. För verkligt säker körning rekommenderas dock byte i god tid innan gränsen nås — sommardäck bör bytas vid cirka 3 mm för att minimera risken för vattenplaning, och vinterdäck bör bytas vid cirka 3–5 mm (gärna minst 4 mm) för att behålla fästet på snö och modd.</p><p>Kontrollera även däckens ålder via den fyrsiffriga DOT-koden på däcksidan. De sista fyra siffrorna visar tillverkningsvecka och tillverkningsår — till exempel anger 2421 vecka 24 år 2021. Gummi är en färskvara som åldras och hårdnar med tiden. Däck äldre än 6–10 år bör bytas ut oavsett kvarvarande mönsterdjup, eftersom åldrat gummi förlorar sin elasticitet och inte längre greppar vägbanan säkert.</p><p>Gör det till en vana att regelbundet syna däcken efter sprickor, utbuktningar, ojämnt slitage och främmande föremål. Är du osäker på däckens skick eller ålder är du alltid välkommen in till oss på Brynäs Bilservice för en fackmässig bedömning.</p></div></div></div></section>
    <section className="tyres-page__closing" aria-labelledby="tyres-closing-title"><div className="container tyres-page__container"><div className="tyres-page__closing-card"><div className="tyres-page__closing-icon" aria-hidden="true"><ShieldHeartIcon /></div><div><h2 id="tyres-closing-title">Låt oss gå igenom dina hjul</h2><p>Vi hjälper dig att upptäcka skador, felaktigt lufttryck och slitage i tid.</p></div><div className="tyres-page__actions"><button type="button" className="tyres-page__button tyres-page__button--primary" onClick={openModal}>Boka tid</button><a className="tyres-page__button tyres-page__button--outline" href="tel:0705533395">Ring: 070-553 33 95</a></div></div></div></section>
  </main><BookingFormModal isOpen={isModalOpen} onClose={() => setIsModalOpen(false)} /><Footer /></>
}
