#!/usr/bin/env python3
"""Build the icon pool: one cleaned SVG per recommended catalogue motif in four colour variants.

Source: _magnus/icon-candidates (local, git-ignored) + catalogue/CATALOGUE.csv (recommended == 'ja').
Output: client/src/assets/images/icons/pool/<motif>--<variant>.svg and MANIFEST.md.
Variants: dark (original ink + teal), white, teal, amber. Colours are the --bb-* token values.
Vite bundles only what a page imports, so unused pool files cost nothing; prune.py lists them.
Run: python3 docs/audit-harness/icons/build-pool.py   (re-running overwrites the pool)
"""
import csv, re, sys
from pathlib import Path

ROOT = Path(__file__).resolve().parents[3]
SRC = ROOT / '_magnus' / 'icon-candidates'
OUT = ROOT / 'client' / 'src' / 'assets' / 'images' / 'icons' / 'pool'

INK, ACCENT, LARGE = '#071416', '#0ab2c1', '#047784'
# variant -> (ink layer, accent layer, single-fill "large" illustrations)
# (colour, fill-opacity or None). Token values from design-tokens.css.
VARIANTS = {
    'dark':  (('#071416', None), ('#0ab2c1', None), ('#047784', None)),                # original
    'white': (('#ffffff', '.45'), ('#ffffff', None), ('#ffffff', None)),               # two tones by opacity
    'teal':  (('#047784', None), ('#0ab2c1', None), ('#0ab2c1', None)),                # teal-700 + teal-500
    'amber': (('#d48202', None), ('#fca311', None), ('#f09505', None)),                # amber-600 + amber-400 / 500
}

def clean(svg: str) -> str:
    svg = re.sub(r'<\?xml[^>]*\?>', '', svg)
    svg = re.sub(r'<!DOCTYPE[^>]*>', '', svg, flags=re.S)
    svg = re.sub(r'<!--.*?-->', '', svg, flags=re.S)
    svg = re.sub(r'<metadata>.*?</metadata>', '', svg, flags=re.S)
    m = re.search(r'<svg\b[^>]*>', svg, flags=re.S)
    tag = m.group(0)
    if 'viewBox' not in tag:
        raise ValueError('no viewBox')
    vb = re.search(r'viewBox="([^"]+)"', tag).group(1)
    new = f'<svg xmlns="http://www.w3.org/2000/svg" viewBox="{vb}" preserveAspectRatio="xMidYMid meet">'
    svg = svg.replace(tag, new)
    svg = re.sub(r'\s+', ' ', svg).strip()
    return svg + '\n'

def recolour(svg: str, variant: str, single: bool) -> str:
    ink, accent, large = VARIANTS[variant]
    def fill(c): return f'fill="{c[0]}"' + (f' fill-opacity="{c[1]}"' if c[1] else '')
    if single:
        return svg.replace(f'fill="{LARGE}"', fill(large))
    return svg.replace(f'fill="{INK}"', fill(ink)).replace(f'fill="{ACCENT}"', fill(accent))

def main():
    rows = [r for r in csv.DictReader(open(SRC / 'catalogue' / 'CATALOGUE.csv')) if r['recommended'] == 'ja']
    OUT.mkdir(parents=True, exist_ok=True)
    for f in OUT.glob('*.svg'):
        f.unlink()
    manifest, total = [], 0
    for r in rows:
        raw = (SRC / r['folder'] / f"{r['name']}.svg").read_text()
        svg = clean(raw)
        single = INK not in svg
        if single and LARGE not in svg:
            sys.exit(f"unexpected colours in {r['id']}")
        for v in VARIANTS:
            out = recolour(svg, v, single)
            (OUT / f"{r['motif']}--{v}.svg").write_text(out)
            total += len(out)
        manifest.append(r | {'bytes': len(svg), 'single': single})
    lines = [
        '# Icon pool (staging)', '',
        'Generated by `docs/audit-harness/icons/build-pool.py` from the local catalogue; do not edit by hand.',
        'Files: `<motif>--dark|white|teal|amber.svg`. Use any of them as a `background-image`, or as a `mask-image` source '
        '(the shape is what counts) with a token or gradient as the background. Two-tone variants: ink layer `.ink`, accent `.accent`; '
        'white uses opacity for the second tone.', '',
        '**Needs Maher** = promise or unconfirmed service: do not show on a public page until Magnus says so.',
        '**Prune before launch:** `python3 docs/audit-harness/icons/prune.py` lists pool files nothing imports; `--delete` removes them.', '',
        '| Motif | Category | Size tier | Quality | Single colour | Needs Maher | Note |', '|---|---|---|---|---|---|---|',
    ]
    for r in sorted(manifest, key=lambda x: (x['category'], x['motif'])):
        lines.append(f"| {r['motif']} | {r['category']} | {r['tier']} | {r['quality']} | {'yes' if r['single'] else ''} | {r['needs_maher']} | {r['flag']} |")
    (OUT / 'MANIFEST.md').write_text('\n'.join(lines) + '\n')
    print(f"{len(rows)} motifs, {len(rows)*len(VARIANTS)} files, {total/1024:.0f} KB")

main()
