import { useEffect, useState } from 'react'
import type { FormEvent, ReactNode } from 'react'
import { Link } from 'react-router-dom'
import { BookingFormModal } from '../../components/BookingForm'
import { PublicHeader } from '../../components/layout/PublicHeader'
import { PublicFooter } from '../../components/layout/PublicFooter'
import heroWebp from '../../assets/images/home/landing-v2/landing-sundown-hero.webp'
import heroJpg from '../../assets/images/home/landing-v2/landing-sundown-hero.jpg'
import { GalleryTeaserCard } from '../../components/ui/GalleryTeaserCard'
import mechanicDiagnostic from '../../assets/images/services/diagnostics/diagnostics-mechanic-laptop-workshop.webp'
import wrenchWorkbench from '../../assets/images/services/general/wrench-and-bolt-workbench.webp'
import tireStorage from '../../assets/images/services/tires/tire-storage-rack.webp'
import acManometers from '../../assets/images/services/ac/ac-manometers-on-engine.jpg'
import vehicleForSale from '../../assets/images/vehicles/peugeot-307-cc/peugeot-307-cc-side-profile.webp'
import './LandingPage.css'

type IconName = 'calendar' | 'phone' | 'mail' | 'pin' | 'arrow' | 'wrench' | 'monitor' | 'wheel' | 'snowflake' | 'chat' | 'shield' | 'clock' | 'send' | 'facebook' | 'car' | 'check'

function Icon({ name, className = '' }: { name: IconName; className?: string }) {
  const common = { className, viewBox: '0 0 24 24', fill: 'none', stroke: 'currentColor', strokeWidth: 2, strokeLinecap: 'round' as const, strokeLinejoin: 'round' as const, 'aria-hidden': true }
  const paths: Record<IconName, ReactNode> = {
    calendar: <><path d="M7 3v3M17 3v3M4 9h16" /><rect x="4" y="5" width="16" height="15" rx="2" /><path d="M8 13h2M14 13h2M8 17h2M14 17h2" /></>,
    phone: <path d="M21 16.8v3a2 2 0 0 1-2.2 2 19.5 19.5 0 0 1-8.5-3.1A19 19 0 0 1 4.3 12a19.5 19.5 0 0 1-3.1-8.5A2 2 0 0 1 3.2 1.3h3a2 2 0 0 1 2 1.7c.1 1 .4 1.9.7 2.8a2 2 0 0 1-.5 2.1l-.9.9a16 16 0 0 0 6 6l.9-.9a2 2 0 0 1 2.1-.5c.9.4 1.8.6 2.8.8a2 2 0 0 1 1.7 2.1Z" />,
    mail: <><rect x="2" y="4" width="20" height="16" rx="2" /><path d="m2 7 9 5.7a2 2 0 0 0 2 0L22 7" /></>,
    pin: <><path d="M20.5 10c0 6.5-8.5 12-8.5 12S3.5 16.5 3.5 10a8.5 8.5 0 1 1 17 0Z" /><circle cx="12" cy="10" r="2.5" /></>,
    arrow: <><path d="M5 12h14" /><path d="m13 6 6 6-6 6" /></>,
    wrench: <path d="M14.8 6.2a1 1 0 0 0 0 1.4l1.6 1.6a1 1 0 0 0 1.4 0l3.8-3.8a6 6 0 0 1-8 8l-6.9 6.9a2.1 2.1 0 0 1-3-3l6.9-6.9a6 6 0 0 1 8-8l-3.8 3.7Z" />,
    monitor: <><rect x="2" y="3" width="20" height="14" rx="2" /><path d="M8 21h8M12 17v4" /></>,
    wheel: <><circle cx="12" cy="12" r="9.5" /><circle cx="12" cy="12" r="3" /><path d="M12 2.5v6.5M21.5 12H15M12 21.5V15M2.5 12H9" /></>,
    snowflake: <><path d="M12 2v20M2 12h20M4.9 4.9l14.2 14.2M4.9 19.1 19.1 4.9" /><path d="m8 2 4 4 4-4M8 22l4-4 4 4M2 8l4 4-4 4M22 8l-4 4 4 4" /></>,
    chat: <><path d="M20 11.5a7.8 7.8 0 0 1-8 7.5 8.6 8.6 0 0 1-3.5-.7L4 20l1.3-3.6A7.3 7.3 0 0 1 4 12a7.8 7.8 0 0 1 8-7.5 7.8 7.8 0 0 1 8 7Z" /><path d="M8 12h.01M12 12h.01M16 12h.01" /></>,
    shield: <><path d="M12 3 20 6v5c0 5-3.5 8.4-8 10-4.5-1.6-8-5-8-10V6l8-3Z" /><path d="m8.5 12 2.2 2.2 4.8-5" /></>,
    clock: <><circle cx="12" cy="12" r="9" /><path d="M12 7v5l3 2" /></>,
    send: <><path d="m22 2-7 20-4-9-9-4 20-7Z" /><path d="m22 2-11 11" /></>,
    facebook: <path d="M18 2h-3a5 5 0 0 0-5 5v3H7v4h3v8h4v-8h3l1-4h-4V7a1 1 0 0 1 1-1h3z" />,
    car: <><path d="m5 17-1 3M19 17l1 3M3 13l2.4-6.1A2 2 0 0 1 7.2 5.5h9.6a2 2 0 0 1 1.8 1.4L21 13v5a1 1 0 0 1-1 1H4a1 1 0 0 1-1-1v-5Z" /><path d="M3 13h18M7 16h.01M17 16h.01" /></>,
    check: <path d="m5 12 4.2 4.2L19 6.5" />,
  }
  return <svg {...common}>{paths[name]}</svg>
}

function Star({ size = 15 }: { size?: number }) {
  return <svg width={size} height={size} viewBox="0 0 24 24" fill="#FBBC04" stroke="#FBBC04" strokeWidth="1.2" aria-hidden="true"><path d="m12 2 3.1 6.3 6.9 1-5 4.9 1.2 6.8-6.2-3.2-6.2 3.2 1.2-6.8-5-4.9 6.9-1L12 2Z" /></svg>
}

const reviews = [{ name: 'Inge', text: 'Fantastisk hjälp när vi hade bilproblem runt jul. Hjälpte till att ordna en hyrbil så att vi kunde fortsätta vår resa.' }, { name: 'Olle Blomgren', text: 'Fick problem med bromsok när jag var på väg hem efter semestern. Snabbt, schysst och professionellt.' }, { name: 'J. Niva', text: 'Utmärkt kundbemötande och bra priser. Har haft min bil på service och reparationer här flera gånger.' }, { name: 'Gunilla Lövgren', text: 'Mycket bra jobb, bra kundbemötande och hjälpsamma med beställning av tillbehör.' }]
const services = [
  { title: 'Bilservice och reparationer', desc: 'Underhåll, oljebyte, bromsar, kamrem och mekaniska reparationer.', to: '/service-reparationer#bilservice', icon: 'wrench' as const, image: wrenchWorkbench },
  { title: 'Felsökning och diagnostik', desc: 'Felkodsläsning och noggrann analys av modern fordonselektronik.', to: '/felsokning', icon: 'monitor' as const, image: mechanicDiagnostic },
  { title: 'Däckservice och däckhotell', desc: 'Däckskifte, balansering, hjulinställning och förvaring.', to: '/dackservice', icon: 'wheel' as const, image: tireStorage },
  { title: 'AC-service', desc: 'Felsökning, provtryckning och påfyllning för god kupékomfort.', to: '/ac-service', icon: 'snowflake' as const, image: acManometers },
]
const process = [['01', 'Bokning och inlämning', 'Du bokar en tid som passar din bil.'], ['02', 'Initial kontroll', 'Vi gör en första bedömning av behovet.'], ['03', 'Service enligt checklista', 'Arbetet följer den servicenivå som är aktuell.'], ['04', 'Godkännande vid extraarbete', 'Vi kontaktar dig innan vi går vidare.'], ['05', 'Slutkontroll och rapport', 'Du får en genomgång när bilen är klar.']]

function LandingReviews() {
  const [active, setActive] = useState(0)
  useEffect(() => { if (window.matchMedia('(prefers-reduced-motion: reduce)').matches) return; const timer = window.setInterval(() => setActive(index => (index + 1) % reviews.length), 8000); return () => window.clearInterval(timer) }, [])
  const review = reviews[active]
  return <a className="landing-v2__reviews" href="https://maps.app.goo.gl/rXR1nz2RwaUQcvuW9" target="_blank" rel="noopener noreferrer" aria-label="Brynäs Bilservice har betyget 4,3 av 5 baserat på 50 omdömen. Läs omdömena på Google Maps."><div className="landing-v2__rating"><strong>4,3</strong><span className="landing-v2__stars">{[1, 2, 3, 4, 5].map(star => <Star key={star} />)}</span><small>50 recensioner</small></div><div className="landing-v2__google"><b>Google</b><small>Omdömen på Google Maps</small></div><div className="landing-v2__review"><span className="landing-v2__review-avatar">{review.name[0]}</span><div className="landing-v2__review-author"><b>{review.name}</b><span className="landing-v2__stars">{[1, 2, 3, 4, 5].map(star => <Star key={star} size={13} />)}</span></div><p>{review.text}</p></div></a>
}

function ContactForm() {
  const [submitted, setSubmitted] = useState(false)
  const submit = (event: FormEvent<HTMLFormElement>) => { event.preventDefault(); setSubmitted(true) }
  if (submitted) return <div className="landing-v2__form-success" role="status"><span>✓</span><h3>Tack för ditt meddelande!</h3><p>Vi har tagit emot din förfrågan och återkommer så snart vi kan under våra öppettider.</p><button type="button" onClick={() => setSubmitted(false)}>Skicka ett till meddelande</button></div>
  return <form className="landing-v2__form" onSubmit={submit}><div className="landing-v2__form-grid"><label>Namn <span>*</span><input required name="name" placeholder="Ditt namn" autoComplete="name" /></label><label>E-post <span>*</span><input required type="email" name="email" placeholder="din@epost.se" autoComplete="email" /></label><label>Telefon<input type="tel" name="phone" placeholder="07X - XXX XX XX" autoComplete="tel" /></label><label>Ärende<select name="subject" defaultValue=""><option value="">Välj ärende</option><option>Bilservice & oljebyte</option><option>Reparation & felsökning</option><option>Däckservice & hjulinställning</option><option>AC-service</option><option>Bärgning & transport</option><option>Övrigt</option></select></label></div><label className="landing-v2__form-message">Meddelande <span>*</span><textarea required name="message" rows={4} placeholder="Skriv ditt meddelande här..." /></label><button className="landing-v2__form-submit" type="submit">Skicka meddelande <Icon name="send" /></button></form>
}

export default function LandingPage() {
  const [bookingOpen, setBookingOpen] = useState(false)
  return <main className="landing-v2"><section className="landing-v2__hero" aria-labelledby="landing-v2-hero-title"><picture className="landing-v2__hero-media"><source srcSet={heroWebp} type="image/webp" /><img src={heroJpg} alt="Honda CR-V i verkstaden vid solnedgång" /></picture><div className="landing-v2__hero-shade" aria-hidden="true" /><PublicHeader onBookingClick={() => setBookingOpen(true)} variant="overlay" /><div className="landing-v2__wrap landing-v2__hero-content"><div className="landing-v2__hero-copy"><p className="landing-v2__hero-eyebrow">Din bilverkstad i Brynäs, Gävle</p><h1 id="landing-v2-hero-title"><span>Din bil</span><span className="landing-v2__accent">förtjänar</span><span>det bästa</span></h1><p>Brynäs Bilservice är din lokala, oberoende verkstad i Gävle. Vi utför all typ av service och reparation – för alla bilmärken, till konkurrenskraftiga priser.</p><div className="landing-v2__hero-actions"><button className="landing-v2__book" type="button" onClick={() => setBookingOpen(true)}><Icon name="calendar" />Boka tid</button><a className="landing-v2__call" href="tel:+46705533395"><Icon name="phone" />Ring oss nu</a></div></div><div className="landing-v2__hero-bottom"><div className="landing-v2__trust-row"><div><i><Icon name="shield" /></i><span><b>Personlig service</b><small>Du och din bil i fokus.</small></span></div><div><i><Icon name="wrench" /></i><span><b>Erfarna mekaniker</b><small>Mångårig erfarenhet.</small></span></div><div><i><Icon name="clock" /></i><span><b>Tryggt och enkelt</b><small>Från bokning till färdig bil.</small></span></div></div><LandingReviews /></div></div></section>

  <section className="landing-v2__contact-section" aria-labelledby="landing-v2-contact-title"><svg className="landing-v2__contact-art" viewBox="0 0 450 450" fill="none" aria-hidden="true"><path d="M75 140C50 115 50 75 75 50c25-25 65-25 90 0 15 15 20 35 15 55l80 80-35 35-80-80c-20 5-40 0-55-15Z" /><circle cx="90" cy="360" r="140" /><circle cx="90" cy="360" r="200" /></svg><div className="landing-v2__wrap landing-v2__contact-grid"><div className="landing-v2__contact-copy"><h2 id="landing-v2-contact-title">Hör av dig<br /><span className="landing-v2__accent">till oss</span></h2><p>Har du frågor, vill boka tid eller behöver rådgivning? Skicka ett meddelande så återkommer vi så snart vi kan.</p><div className="landing-v2__contact-list"><a href="tel:+46705533395"><i><Icon name="phone" /></i><span><small>Ring oss</small><b>070–553 33 95</b></span></a><a href="mailto:info@brynasbilservice.se"><i><Icon name="mail" /></i><span><small>Mejla oss</small><b>info@brynasbilservice.se</b></span></a><a href="https://maps.google.com/?q=Utmarksv%C3%A4gen+21B+G%C3%A4vle" target="_blank" rel="noopener noreferrer"><i><Icon name="pin" /></i><span><small>Besök oss</small><b>Utmarksvägen 21B<br />802 91 Gävle</b></span></a></div><p className="landing-v2__contact-note">Fyll i formuläret så återkommer vi till dig så snart som möjligt!</p></div><div className="landing-v2__form-card"><h2>Skicka ett meddelande</h2><p>Berätta hur vi kan hjälpa dig. Obligatoriska fält är markerade med *.</p><ContactForm /></div></div></section>

  <section className="landing-v2__why-section" aria-labelledby="landing-v2-why-title"><img src={mechanicDiagnostic} alt="Mekaniker som arbetar med diagnostik i verkstaden" /><div className="landing-v2__why-shade" aria-hidden="true" /><div className="landing-v2__wrap landing-v2__why-content"><div><p className="landing-v2__eyebrow landing-v2__eyebrow--dark">Varför välja Brynäs Bilservice?</p><h2 id="landing-v2-why-title">Trygg bilservice<br />i <span className="landing-v2__accent">lokala Gävle</span></h2><p>Vi kombinerar erfarenhet, noggrannhet och ett personligt bemötande – oavsett om det gäller en enkel service eller en mer omfattande reparation.</p><Link className="landing-v2__book" to="/om-oss">Läs mer om oss <Icon name="arrow" /></Link></div><ul><li><i><Icon name="chat" /></i><span><b>Tydlig kommunikation</b><small>Vi håller dig uppdaterad genom hela processen.</small></span></li><li><i><Icon name="shield" /></i><span><b>Omsorg om din bil</b><small>Vi arbetar noggrant och med rätt kunskap.</small></span></li><li><i><Icon name="wrench" /></i><span><b>Personlig service</b><small>Du och din bil är alltid i fokus.</small></span></li><li><i><Icon name="pin" /></i><span><b>Lokal verkstad</b><small>Nära dig i Brynäs, Gävle.</small></span></li></ul></div></section>

  <section className="landing-v2__services-section" aria-labelledby="landing-v2-services-title"><div className="landing-v2__wrap landing-v2__services-layout"><header><p className="landing-v2__eyebrow">Vad vi hjälper dig med</p><h2 id="landing-v2-services-title">Service för<br /><span className="landing-v2__accent">hela bilen</span></h2><p>Vi utför allt från regelbunden service och mekaniska reparationer till avancerad diagnostik, däckservice och AC-service för alla bilmärken.</p><Link className="landing-v2__book" to="/biltjanster">Se alla tjänster <Icon name="arrow" /></Link></header><div className="landing-v2__service-grid">{services.map(service => <Link key={service.to} to={service.to} className="landing-v2__service-card"><img src={service.image} alt="" /><div className="landing-v2__service-card-shade" /><div className="landing-v2__service-card-content"><i><Icon name={service.icon} /></i><h3>{service.title}</h3><p>{service.desc}</p><span><Icon name="arrow" /></span></div></Link>)}</div></div></section>

  <section className="landing-v2__process-section" aria-labelledby="landing-v2-process-title"><img src={wrenchWorkbench} alt="Arbetsbänk med verktyg i Brynäs Bilservice verkstad" /><div className="landing-v2__process-shade" aria-hidden="true" /><div className="landing-v2__wrap landing-v2__process-content"><div><p className="landing-v2__eyebrow landing-v2__eyebrow--dark">Så går det till</p><h2 id="landing-v2-process-title">Så går det till<br /><span className="landing-v2__accent">hos oss</span></h2><p>Att förstå processen gör det enklare att veta vad som händer med bilen och varför en service ibland behöver ta lite tid.</p><a className="landing-v2__book" href="tel:+46705533395"><Icon name="phone" />Ring oss: 070–553 33 95</a></div><ol>{process.map(([number, title, text]) => <li key={number}><b>{number}</b><i><Icon name={number === '01' ? 'calendar' : number === '02' ? 'monitor' : number === '03' ? 'wrench' : number === '04' ? 'car' : 'check'} /></i><h3>{title}</h3><p>{text}</p></li>)}</ol></div></section>

  <section className="landing-v2__about-section" aria-labelledby="landing-v2-about-title"><div className="landing-v2__wrap landing-v2__about-grid"><GalleryTeaserCard /><div className="landing-v2__about-copy"><p className="landing-v2__eyebrow">Om Brynäs Bilservice</p><h2 id="landing-v2-about-title">Lokal verkstad.<br /><span className="landing-v2__accent">Personlig service.</span></h2><p>Brynäs Bilservice grundades 2021 och är din lokala, oberoende verkstad i Brynäs, Gävle. Vi brinner för bilar och för människorna som kör dem. Hos oss möts du av erfarenhet, noggrannhet och ett personligt bemötande – oavsett om det gäller en enkel service eller en mer omfattande reparation.</p><p>Vi servar alla bilmärken. Hittar vi något extra under arbetet kontaktar vi alltid dig först – inga överraskningar på fakturan.</p><Link className="landing-v2__book" to="/om-oss">Läs mer om oss <Icon name="arrow" /></Link></div></div></section>

  <section className="landing-v2__cars-section" aria-labelledby="landing-v2-cars-title"><img src={vehicleForSale} alt="Begagnad bil till salu hos Brynäs Bilservice" /><div className="landing-v2__cars-shade" aria-hidden="true" /><div className="landing-v2__wrap landing-v2__cars-content"><div><p className="landing-v2__eyebrow landing-v2__eyebrow--dark">Kvalitetskontrollerade fordon</p><h2 id="landing-v2-cars-title">Letar du efter en <span className="landing-v2__accent">begagnad bil?</span></h2><p>Vi säljer även noggrant genomgångna och besiktigade begagnade bilar i Gävle. Varje bil kontrolleras av våra mekaniker innan försäljning.</p><Link className="landing-v2__book" to="/bilar-till-salu">Se bilar till salu <Icon name="arrow" /></Link></div></div></section>

  <section className="landing-v2__closing-section" aria-labelledby="landing-v2-closing-title"><div className="landing-v2__wrap"><div className="landing-v2__closing-card"><div className="landing-v2__closing-copy"><p className="landing-v2__eyebrow landing-v2__eyebrow--dark">Kontakt & öppettider</p><h2 id="landing-v2-closing-title">Behöver din bil <span className="landing-v2__accent">hjälp?</span></h2><p>Boka tid online eller ring oss direkt så hjälper vi dig att hitta en tid som passar.</p><div><button className="landing-v2__book" type="button" onClick={() => setBookingOpen(true)}>Boka tid <Icon name="arrow" /></button><a className="landing-v2__call" href="tel:+46705533395"><Icon name="phone" />Ring: 070–553 33 95</a></div></div><aside className="landing-v2__closing-panel"><div><i><Icon name="pin" /></i><span><small>Besöksadress</small><b>Utmarksvägen 21B, 802 91 Gävle</b><a href="https://maps.google.com/?q=Utmarksv%C3%A4gen+21B+G%C3%A4vle" target="_blank" rel="noopener noreferrer">Öppna i Google Maps →</a></span></div><div className="landing-v2__closing-panel-row"><div><i><Icon name="phone" /></i><span><small>Telefon</small><a href="tel:+46705533395">070–553 33 95</a></span></div><div><i><Icon name="mail" /></i><span><small>E-post</small><a href="mailto:info@brynasbilservice.se">info@brynasbilservice.se</a></span></div></div><div><i><Icon name="clock" /></i><span><small>Öppettider</small><dl><div><dt>Måndag – Fredag</dt><dd>08:00 – 17:00</dd></div><div><dt>Lördag</dt><dd>Förfrågan</dd></div><div><dt>Söndag</dt><dd>Stängt</dd></div></dl></span></div></aside></div></div></section>

  <PublicFooter onBookingClick={() => setBookingOpen(true)} /><BookingFormModal isOpen={bookingOpen} onClose={() => setBookingOpen(false)} /></main>
}
